### ISSUE TITLE
Study spaces: name of library needs to be bolder

### ISSUE THREAD

**Issue by matt-bernhardt** [mitlibraries-ux/MITlibraries-parent#14]
(this item has been copied from Basecamp) 

http://libraries.mit.edu/study
See page 11 of styling doc.

Library names need to be bolder everywhere, including hours & individual library pages. Consider making them bolder, as on /locations.

**Comment by matt-bernhardt** [comment]
Library names on Study page:
![fireshot screen capture 166 - study spaces i mit libraries - libraries_mit_edu_study](https://cloud.githubusercontent.com/assets/1403248/6414719/8eb88c48-be67-11e4-913e-7737dda4d4ea.png)

Library names on Location page:
![fireshot screen capture 165 - map of locations i mit libraries - libraries_mit_edu_locations](https://cloud.githubusercontent.com/assets/1403248/6414718/8eb68f2e-be67-11e4-8b50-3db4e0b1c60d.png)

**Comment by matt-bernhardt** [comment]
This issue on Basecamp can be found here: https://basecamp.com/2612667/projects/7659395/todos/139497644

**Comment by melissaspiegel** [comment]
global 4640

h3 {
font-weight: 400;
padding-bottom: 3px;
padding-top: 0px;
margin-top: 0px;
margin-bottom: 0px;
}
