### ISSUE TITLE
Throughout sites: adjust line height in paragraphs & bulleted lists.

### ISSUE THREAD

**Issue by matt-bernhardt** [mitlibraries-ux/MITlibraries-parent#15]
Line height is too big within paragraphs & lists.

Maybe add more space below bulleted lists (space seems bigger above the list than below.) (Paragraphs automatically have margins below them, but lists don't.)

Examples:
http://libraries.mit.edu/about/
http://libraries.mit.edu/research-support/

This also affects child themes:
http://libraries.mit.edu/future-spaces

**Comment by matt-bernhardt** [comment]
This issue on Basecamp can be found here:
https://basecamp.com/2612667/projects/7659395/todos/145207214

**Comment by melissaspiegel** [comment]
global 195
.entry-content ul li {
list-style: disc;
margin-bottom: 5px;
line-height: 23px;
}
