### ISSUE TITLE
Individual location pages: Make sub-headers h3s, with appropriate spacing below/above to make them look like headers

### ISSUE THREAD

**Issue by matt-bernhardt** [mitlibraries-ux/MITlibraries-parent#16]
Sample page: http://libraries.mit.edu/dewey

See page 1 of styling doc.

---

Ex. See http://libraries.mit.edu/barker - in "Research Guides: tools & databases..." column, the "Engineering" (h4) needs more space around it.

---
1. h3's need to be bolder
2. ul's need padding under them 
3. h4's should be a little bolder

Example: http://libraries-dev.mit.edu/rotch

**Comment by matt-bernhardt** [comment]
This issue on Basecamp can be found here:
https://basecamp.com/2612667/projects/7659395/todos/139497489

**Comment by melissaspiegel** [comment]
Melissa Spiegel 
ul's need padding under them 
global.css  
line 291
ul.arrows {
margin-bottom: 20px;
}

---

h3's need to be bolder
global.css  
line 4640
h3 {font-weight: 400;
padding-bottom: 3px;
padding-top: 0px;
margin-top: 0px;
margin-bottom: 0px;
}

---

h4's should be a little bolder
h4 have a <strong> in the html not ideal 
Location Template
page-location.php
