### ISSUE TITLE
Lists: improve spacing and styling

### ISSUE THREAD

**Issue by matt-bernhardt** [mitlibraries-ux/MITlibraries-parent#17]
See page 7 of styling doc for details:
Maybe smaller line-height, 

Example: 
http://libraries.mit.edu/barker/media-room

**Comment by matt-bernhardt** [comment]
This is the production version of the above URL, viewed on Firefox:
![fireshot screen capture 167 - barker media room i mit libraries - libraries_mit_edu_barker_media-room](https://cloud.githubusercontent.com/assets/1403248/6415207/846adb2a-be6b-11e4-8bf5-43f4eac5004a.png)

**Comment by matt-bernhardt** [comment]
On Basecamp, this issue can be found here:
https://basecamp.com/2612667/projects/7659395/todos/139497543

**Comment by melissaspiegel** [comment]
global 170
.entry-content p, p {
margin-bottom: 10px!important;
}
