### ISSUE TITLE
Individual location pages: Left column should be much thinner, and the middle column larger

### ISSUE THREAD

**Issue by matt-bernhardt** [mitlibraries-ux/MITlibraries-parent#19]
Sample page: http://libraries.mit.edu/dewey

See page 1 of styling doc.

**Comment by matt-bernhardt** [comment]
This issue comes from Basecamp at:
https://basecamp.com/2612667/projects/7659395/todos/139497487

**Comment by melissaspiegel** [comment]
global 4636
.locationPage .tab2 .first {
width: 20%;
}

global 4638

.locationPage .tab .second {
width: 70%;
}

**Comment by matt-bernhardt** [comment]
It looks like the span# classes aren't available for use. Removing the explicit widths causes them to be auto-calculated. Further inspection shows that the span# classes are included in the FontAwesome documentation styles, which aren't included in our build process. Adding those files could have far-reaching repercussions at this stage, so I think the best process may be to explicitly add those widths back.

It may also be necessary to remove the span\* values from the template to prevent future confusion.
